version: '2.4'

services:
  backend:
    build:
      context: .
    volumes:
      - ./backend:/app
    ports:
        - 8000:8000
    depends_on:
      - db
      - memcached
    environment:
      DB_ENGINE: "django.db.backends.postgresql"
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_PORT: ${DB_PORT:-5432}
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - DB_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ../volumes/postgres:/var/lib/postgresql
  memcached:
    image: memcached:1-alpine
    command: memcached -m 300 
    restart: always
